import React from 'react'
import CIcon from '@coreui/icons-react'



export default [
  {
    id: 'ef97e4d3-864c-11eb-8d12-06e672dcd768',
    isvisbale: true,
    _tag: 'CSidebarNavItem',
    name: 'Dashboard',
    to: '/dashboard',
    icon: <CIcon name="cil-speedometer" customClasses="c-sidebar-nav-icon" />,
    badge: {
      color: 'info',
      text: 'NEW',
    }
  }, {
    id: '00b4bc3f-864d-11eb-8d12-06e672dcd768',
    isvisbale: true,
    _tag: 'CSidebarNavItem',
    name: 'Boat Status',
    to: '/boatstatus',
    icon: <CIcon name="boat" customClasses="c-sidebar-nav-icon" />,
  },
  {
    id: "08279d4a-864d-11eb-8d12-06e672dcd768",
    isvisbale: true,
    _tag: 'CSidebarNavItem',
    name: 'Booking',
    to: '/bookinghistory',
    icon: <CIcon name="boat" customClasses="c-sidebar-nav-icon" />,
  },
  {
    id: "Master",
    isvisbale: true,
    _tag: 'CSidebarNavTitle',
    _children: ['Master']
  },
  {
    id: 'c29a6e40-cda3-11eb-8d12-06e672dcd768',
    isvisbale: true,
    menuid: 1,
    _tag: 'CSidebarNavItem',
    name: 'Role Master',
    to: '/role',
    icon: 'cil-settings',
  },
  {
    id: '1954424f-864d-11eb-8d12-06e672dcd768',
    isvisbale: true,
    menuid: 1,
    _tag: 'CSidebarNavItem',
    name: 'User Master',
    to: '/users',
    icon: 'cil-user',
  },
  {
    id: '1e0fd14c-864d-11eb-8d12-06e672dcd768',
    isvisbale: true,
    _tag: 'CSidebarNavItem',
    name: 'Fees Master',
    to: '/fees',
    icon: 'cil-dollar',
  },
  {
    id: '325ec989-864d-11eb-8d12-06e672dcd768',
    isvisbale: true,
    menuid: 1,
    _tag: 'CSidebarNavItem',
    name: 'Slot Master',
    to: '/slot',
    icon: 'cil-clock',
  },
  {
    id: '3cf44648-864d-11eb-8d12-06e672dcd768',
    isvisbale: true,
    menuid: 1,
    _tag: 'CSidebarNavItem',
    name: 'Boat Master',
    to: '/boat',
    icon: <CIcon name="boat" customClasses="c-sidebar-nav-icon" />,
  },
  {
    id: '44eea69d-864d-11eb-8d12-06e672dcd768',
    isvisbale: true,
    menuid: 1,
    _tag: 'CSidebarNavItem',
    name: 'Vehicle Master',
    to: '/vehicle',
    icon: <CIcon name="vehicleicon" customClasses="c-sidebar-nav-icon" />,
  },
  {
    id: '4e2aef02-864d-11eb-8d12-06e672dcd768',
    isvisbale: true,
    menuid: 1,
    _tag: 'CSidebarNavItem',
    name: 'Discount Master',
    to: '/discount',
    icon: <CIcon name="discounticon" customClasses="c-sidebar-nav-icon" />,
  }, {
    id: '5968e993-864d-11eb-8d12-06e672dcd768',
    isvisbale: true,
    menuid: 1,
    _tag: 'CSidebarNavItem',
    name: 'Port Master',
    to: '/port',
    menuid: 1,
    icon: <CIcon name="port" customClasses="c-sidebar-nav-icon" />,
  },
  {
    id: '604351b6-864d-11eb-8d12-06e672dcd768',
    isvisbale: true,
    menuid: 1,
    _tag: 'CSidebarNavItem',
    name: 'Country Master',
    to: '/country',
    icon: <CIcon name="country" customClasses="c-sidebar-nav-icon" />,
  },
  {
    id: '68a53b1e-864d-11eb-8d12-06e672dcd768',
    isvisbale: true,
    menuid: 1,
    _tag: 'CSidebarNavItem',
    name: 'Citizenship Master',
    to: '/citizenship',
    icon: <CIcon name="cil-user" customClasses="c-sidebar-nav-icon" />,
  }, {
    id: '74ef755e-864d-11eb-8d12-06e672dcd768',
    isvisbale: true,
    menuid: 1,
    _tag: 'CSidebarNavItem',
    name: 'Province Master',
    to: '/province',
    icon: <CIcon name="province" customClasses="c-sidebar-nav-icon" />,
  }, {
    id: "7f6d54c2-864d-11eb-8d12-06e672dcd768",
    menuid: 1,
    isvisbale: true,
    _tag: 'CSidebarNavItem',
    name: 'Municipality Master',
    to: '/municipality',
    icon: <CIcon name="municipality" customClasses="c-sidebar-nav-icon" />,
  },
  {
    id: "88b2d0a9-864d-11eb-8d12-06e672dcd768",
    menuid: 1,
    isvisbale: true,
    _tag: 'CSidebarNavItem',
    name: 'Package Master',
    to: '/package',
    icon: <CIcon name="packageicon" customClasses="c-sidebar-nav-icon" />,
  },
  {
    id: "95b0b241-864d-11eb-8d12-06e672dcd768",
    isvisbale: true,
    menuid: 1,
    _tag: 'CSidebarNavItem',
    name: 'Hotel Master',
    to: '/hotel',
    icon: <CIcon name="hotel" customClasses="c-sidebar-nav-icon" />,
  },
  {
    id: "a2d01644-902b-11eb-8d12-06e672dcd768",
    isvisbale: true,
    menuid: 1,
    _tag: 'CSidebarNavItem',
    name: 'Information Disclaimer Master',
    to: '/IDM',
    icon: <CIcon name="cil-pencil" customClasses="c-sidebar-nav-icon" />,
  },

  {
    id: "658aa23a-906e-11eb-8d12-06e672dcd768",
    isvisbale: true,
    menuid: 1,
    _tag: 'CSidebarNavItem',
    name: 'List of Accredited Resort ',
    to: '/LARCD',
    icon: <CIcon name="cil-pencil" customClasses="c-sidebar-nav-icon" />,
  },
  {
    id: "90584e3b-906e-11eb-8d12-06e672dcd768",
    isvisbale: true,
    menuid: 1,
    _tag: 'CSidebarNavItem',
    name: 'Payment Procedure',
    to: '/PP',
    icon: <CIcon name="cil-pencil" customClasses="c-sidebar-nav-icon" />,
  },
  {
    id: "a81906ab-906e-11eb-8d12-06e672dcd768",
    isvisbale: true,
    menuid: 1,
    _tag: 'CSidebarNavItem',
    name: 'Refund Procedure',
    to: '/RP',
    icon: <CIcon name="cil-pencil" customClasses="c-sidebar-nav-icon" />,
  },
  {
    id: "c612044c-906e-11eb-8d12-06e672dcd768",
    isvisbale: true,
    menuid: 1,
    _tag: 'CSidebarNavItem',
    name: 'Penalty Clause',
    to: '/PC',
    icon: <CIcon name="cil-pencil" customClasses="c-sidebar-nav-icon" />,
  },
  {
    id: "6e2df0f1-98ef-11eb-8d12-06e672dcd768",
    isvisbale: true,
    menuid: 1,
    _tag: 'CSidebarNavItem',
    name: 'FAQs',
    to: '/FAQs',
    icon: <CIcon name="cil-pencil" customClasses="c-sidebar-nav-icon" />,
  },
  {
    id: "8bec7a6e-98ef-11eb-8d12-06e672dcd768",
    isvisbale: true,
    menuid: 1,
    _tag: 'CSidebarNavItem',
    name: 'Tourism Policy',
    to: '/TP',
    icon: <CIcon name="cil-pencil" customClasses="c-sidebar-nav-icon" />,
  },

  //   
  // 
  {
    id: "Report",
    isvisbale: true,
    _tag: 'CSidebarNavTitle',
    _children: ['Report']
  },
  {
    id: "afc1a94d-864d-11eb-8d12-06e672dcd768",
    isvisbale: true,
    menuid: 2,
    _tag: 'CSidebarNavItem',
    name: 'Transaction Log',
    to: '/report/transactionlog',
  },
  {
    id: "d574cb49-864d-11eb-8d12-06e672dcd768",
    isvisbale: true,
    menuid: 2,
    _tag: 'CSidebarNavItem',
    name: 'Fees Break',
    to: '/report/feebreakdownrpt',
  },
  {
    id: "f90415a8-98f2-11eb-8d12-06e672dcd768",
    isvisbale: true,
    menuid: 2,
    _tag: 'CSidebarNavItem',
    name: 'Tourist Arrivals',
    to: '/icons/coreui-icons',
  },
  {
    id: "a095bb0b-aefd-11eb-8d12-06e672dcd768",
    isvisbale: true,
    menuid: 2,
    _tag: 'CSidebarNavItem',
    name: 'Tourist Visitor',
    to: '/icons/coreui-icons',
  },
  {
    id: "b7fb49f3-aefd-11eb-8d12-06e672dcd768",
    isvisbale: true,
    menuid: 2,
    _tag: 'CSidebarNavItem',
    name: 'Refund',
    to: '/icons/coreui-icons',
  },





]

